FROM node:20-slim
ENV DISPLAY=:0
RUN apt-get update
RUN apt-get install -y libsecret-1-dev dbus dbus-x11 gnome-keyring
RUN mkdir -p /var/run/dbus
RUN dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address